Calculator Component
Obimbo07/math-magicians pull request #2
Opened 2023-09-19 21:49 UTC by Obimbo07

This pull request introduces the following branches 

- Developed just the UI of the calculator.

- Used functional components.

2023-09-19 22:31 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @Obimbo07, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Implemented some project requirements. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-19 22:31 UTC, Qoosim commented on src/components/Calc.js
> +export default Calculator;
- [ ] It is required to have at least one component inside the `Calculator` . You can create a `Button` component and call that component inside the `Calculator` component. Kindly implement that.

### Project Requirement

![button-compo](https://github.com/Obimbo07/math-magicians/assets/26597432/ba8ffa19-1bac-489f-8485-a56652bf9514)

You can look at this snippet below to get some insight :point_down: 

```
  function Button({handleClick}) {
  return (
    <button
      onClick={() => handleClick(value)}
    >
      {value}
    </button>
  );
}
```

```
  <div className={styles.row}>
          <Button value="AC" handleClick={handleClick} />
          <Button value="+/-" handleClick={handleClick} />
          <Button value="%" handleClick={handleClick} />
          <Button value="÷" accent handleClick={handleClick} />
   </div>
```

2023-09-20 08:18 UTC, LionRouge1 requested changes
Hi @Obimbo07, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 08:18 UTC, LionRouge1 commented on src/components/Calc.js
> +};
- [ ] Nice work creating another component for `Button` as suggested by the previous reviewer :clap: However it would be nice to create a different file for this component to follow **React** best practices.

2023-09-20 08:18 UTC, LionRouge1 commented on src/components/Calc.js
> +  // eslint-disable-next-line react/require-default-props
- [ ] Kindly do not disable linters, it helps better your code and helps you follow the standard as well.

2023-09-20 10:48 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Obimbo07,

✔️ Implementation of reusable components

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 10:55 UTC, merged